"""Base word components."""

from .articles import Article, Determiner
from .base import (
    Adjective,
    Adverb,
    AuthoredArtifact,
    ChemicalCompoundName,
    LocationAdjective,
    MartialSocialConcept,
    NauticalShipNameColor,
    NauticalShipNameObject,
    Noun,
    NounForm,
    PrimitiveWeapon,
    Pronoun,
    ShipNameAdjective,
    TimeOfDay,
    UCBerkeleyEmotion,
    Verb,
    VerbTense,
    VillainousPersonNoun,
)

__all__ = [
    "Adjective",
    "Adverb",
    "Article",
    "AuthoredArtifact",
    "ChemicalCompoundName",
    "Determiner",
    "LocationAdjective",
    "MartialSocialConcept",
    "NauticalShipNameColor",
    "NauticalShipNameObject",
    "Noun",
    "NounForm",
    "PrimitiveWeapon",
    "Pronoun",
    "ShipNameAdjective",
    "TimeOfDay",
    "UCBerkeleyEmotion",
    "Verb",
    "VerbTense",
    "VillainousPersonNoun",
]
